### ISSUE TITLE
Create a 'Record Song' component

### ISSUE THREAD

**Issue by adamhannadev** [adamhannadev/quartet#1]
- [ ] In the record song component the user should be able to see the title of the song they have chosen and 2 buttons. A 'Record' button and a 'Reset' button.

- [ ] There should be an audio track of the midi file available for playback.

**Comment by PranavMahesh1** [comment]
![image](https://user-images.githubusercontent.com/8294775/83430572-e3af6000-a403-11ea-8097-753a6ede77cd.png)

Made a mockup layout. Anything to add/move?

**Comment by adamhannadev** [comment]
That's great for now. :)

**Comment by PranavMahesh1** [comment]
https://github.com/adamhannadev/quartet/pull/17
