### ISSUE TITLE
Add recording functionality to 'Record Song' component

### ISSUE THREAD

**Issue by adamhannadev** [adamhannadev/quartet#2]
- [x] When the user clicks the 'Record' button, the browser should prompt the user for access to the microphone,

- [x] Begin recording the user's microphone.

- [x] Wait 4 seconds while playing some kind of 'get ready' animation.

- [x] Play the midi file.

- [x] The user should then be able to click a 'Stop Recording' button that stops the recording.

**Comment by flozender** [comment]
@adamhannadev is this good to go?
