### ISSUE TITLE
Add upload function to 'Record Song' component.

### ISSUE THREAD

**Issue by adamhannadev** [adamhannadev/quartet#3]
- [x] The user should be able to either reset their recording and try again or click an 'Upload' button to upload their song to the server.

- [x] The upload request should include the following data:
- the audio recording
- song title
- user
- part(soprano/alto/tenor/bass)

**Comment by flozender** [comment]
Hey, will you be moving this into the firebase storage?

**Comment by adamhannadev** [comment]
Yes I will. Thanks.
